// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchGeminiModels(arg1) {
  return window['go']['main']['App']['FetchGeminiModels'](arg1);
}

export function FetchOllamaModels() {
  return window['go']['main']['App']['FetchOllamaModels']();
}

export function FetchOpenAIModels(arg1) {
  return window['go']['main']['App']['FetchOpenAIModels'](arg1);
}

export function FetchOpenRouterModels(arg1) {
  return window['go']['main']['App']['FetchOpenRouterModels'](arg1);
}

export function GetAICompletion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAICompletion'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
