// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {providers} from '../models';
import {app} from '../models';
import {models} from '../models';

export function FetchGeminiModels(arg1:string):Promise<Array<providers.Model>>;

export function FetchOllamaModels():Promise<Array<providers.Model>>;

export function FetchOpenAIModels(arg1:string):Promise<Array<providers.Model>>;

export function FetchOpenRouterModels(arg1:string):Promise<Array<providers.Model>>;

export function GetAICompletion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.AICompletionResponse>;

export function GetClipboard():Promise<models.ClipboardResult>;

export function GetRecentCanvases():Promise<models.RecentCanvasesResult>;

export function Greet(arg1:string):Promise<string>;

export function LoadCanvas():Promise<models.CanvasFileResult>;

export function LoadCanvasFromPath(arg1:string):Promise<models.CanvasFileResult>;

export function SaveCanvas(arg1:string):Promise<models.CanvasFileResult>;

export function SetClipboard(arg1:string):Promise<models.ClipboardResult>;
